# Generated by Django 3.2.1 on 2021-11-15 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('correo', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula Ciudadanía'), ('CE', 'Cédula Extranjería'), ('TI', 'Tarjeta Identidad'), ('PP', 'Permiso Permanencia')], default='Otro', max_length=20, verbose_name='Genero')),
                ('cedula', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cedula')),
                ('genero', models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M'), ('Otro', 'Otro')], default='Otro', max_length=20, verbose_name='Genero')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='describir', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Contacto_Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacto Emergencia')),
                ('parentesco_emergercia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Parentesco')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono Emergencia')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
