# Generated by Django 3.2.1 on 2021-11-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='antiguedad',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tiempo en la empresa'),
        ),
    ]
