# Generated by Django 3.2.1 on 2021-11-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incapacidad', '0002_alter_empleado_antiguedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='centro_costo',
            field=models.CharField(default=0, max_length=255, verbose_name='Centro Costo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='antiguedad',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Tiempo en la empresa'),
        ),
    ]
